---
name: Testing

on:
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: make install
        run: |
          make install

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      KIND_CLUSTER_NAME: kuadrant-local
    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
        id: go
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.20.0
          config: utils/kind-cluster.yaml
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}
          wait: 120s
      - name: Check cluster info
        run: |
          kubectl cluster-info dump
      - name: Run make env-setup
        run: |
          make env-setup
      - name: Run tests
        run: |
          make test
      - name: Report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: "*.coverprofile"
